version: '3'

services:
  tasks:
    image: 'blackswan/tasks:latest'
    container_name: tasks
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/TASKS
      - spring.datasource.username=mysql_user
      - spring.datasource.password=mysql_password
      - scheduleRateInSeconds=10
    restart: always

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=TASKS
    healthcheck:
      test:  "/usr/bin/mysql --user=mysql_user --password=mysql_password -e 'SELECT version()'"
      interval: 2s
      retries: 20

